properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${terraform-template}
    branch: master
    events: { "push": true }
inputs:
  - type: git
    path: .tekton
    branch: master
    service: ${schematics-pipeline}
