properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: git
    name: Git PR Trigger
    service: ${terraform-template}
    branch: master
    events:
      pull_request: true
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    properties:
      - type: secure
        name: TF_VAR_ibmcloud_api_key
        value: ${API_KEY}
      - type: text
        name: tf-dir
        value: /
    service: ${terraform-template}
inputs:
  - type: git
    path: .tekton
    branch: master
    service: ${schematics-pipeline}
  - type: git
    path: cra
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: git
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: master
    service: ${tekton-catalog}
